version: "3.1"

services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_DB: backend
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

# adminer is a simple frontend for you to interact with the database
  adminer:
    image: adminer
    ports:
      - 8081:8081

# DATABASE_HOST=localhost
# DATABASE_USER=admin
# DATABASE_PASSWORD=admin
# DATABASE_NAME=backend
# DATABASE_PORT=5432